name: my-nvim-hs
version: 0.1.0.0
github: Futarimiti/nvim
license: WTFPL
author: Carman Fu
maintainer: futarimiti@163.com
copyright: © 2024 Carman Fu
synopsis: Haskell Neovim plugins
category: Neovim

extra-source-files:
  - readme.md

dependencies:
  - base >=4.7 && <5
  - nvim-hs >=2 && <3
  - random
  - unliftio
  - mtl
  - transformers
  - exceptions
  - bytestring
  - containers
  - string-interpolate

default-extensions:
  - ViewPatterns
  - PatternSynonyms
  - StrictData
  - DeriveAnyClass
  - LambdaCase
  - NamedFieldPuns
  - RecordWildCards
  - TypeFamilies
  - OverloadedRecordDot
  - TemplateHaskell
  - QuasiQuotes

ghc-options:
  - -Wall
  - -Wmonomorphism-restriction

description: Personal project to manage plugin dependencies.

source-dirs:
  - .
  - nvim-hs

executables:
  my-nvim-hs:
    main: init.hs
