set mouse=
set nowrap
set path+=**
set fillchars=eob:\ 
set number
set autowrite
set colorcolumn=+1
set cursorline
set shiftwidth=4
set tabstop=4
set noexpandtab
set splitright
set signcolumn=yes:1
set viewoptions-=curdir
set sessionoptions=folds
set nohidden
set noshowmode
set noruler
set shortmess+=FcCmW
set cmdheight=0
set showcmdloc=statusline
set nofoldenable
set keywordprg=
set dictionary=/usr/share/dict/words
